### ISSUE TITLE
Dynamically generating Sitetree based on enabled apps

### ISSUE THREAD

**Issue by LukasMojzis** [idlesign/django-sitetree#105]
Hello, is it possible to somehow generate sitetrees using some mechanism, that could enable INSTALLED_APPS to announce its structures to sitetree?

**Comment by asoupper** [comment]
Hi there, I am very interested in this feature but I can't find a proper way to make it work.
I looked at the documentation: https://django-sitetree.readthedocs.io/en/latest/apps.html#dynamic-sitetree-structuring but I don't understand how to create a 'main' tree with some items and add automatically the sitetrees defined in each app.
Do you have other documentation or sample somewhere?
