### ISSUE TITLE
"sitetree_resync_apps" command works incorrectly 

### ISSUE THREAD

**Issue by dimka665** [idlesign/django-sitetree#135]
Command 'sitetree_resync_apps' creates incorrect site tree after second using.
New tree contains old items and incorrect links in admin.

It's OK if I delete tree from Django admin and run 'sitetree_resync_apps' after it.

Python 3, Django 1.7, sqlite3 db.

**Comment by idlesign** [comment]
Seems to be fixed in master.

**Comment by idlesign** [comment]
Considered closed. Feel free to reopen is not fixed.
