### ISSUE TITLE
Cache problem with mutli user connected

### ISSUE THREAD

**Issue by submarcos** [idlesign/django-sitetree#139]
Hello,

I have a bug on my production server.

I read documentation about cache, So I test different cache backends (FileSystem / Memecached...) and the problem happens.

So, the problem is:
I have a menu configured with URL patterns.
Sometimes, menu generated in templates mix elements of the current user parameter, and another user current parameter. (I see that in my log apps, mixes happens only if another user open another customer base template in same time)

Example: menu items with customer.id parameter.

User A is on Customer 1 Base template.
In same time, User B is on Customer 2 base template.

Menu A should be :
-- /customer/1/ (welcome customer.id)
-- /customer/1/bank/ (bank customer.id)
-- /customer/1/edit/ (edit customer.id)

Menu B should be:
-- /customer/2/ (welcome customer.id)
-- /customer/2/bank/ (bank customer.id)
-- /customer/2/edit/ (edit customer.id)

Sometimes, User B have a menu generated with customer.id as 1 and others with customer.id as 2.
So, If user click on Menu link, it happens that user is not on the good customer.

Menu B is really:
-- /customer/2/ (welcome customer.id)
-- /customer/1/bank/ (bank customer.id)
-- /customer/2/edit/ (edit customer.id)

So, what is the right backend to use to block cache sharing betwen users ?
Is it a bug or configuration problem?

Thanks for your response, It's an emergency for me (CRM with 20000 customers / 80 users in production)

**Comment by idlesign** [comment]
Closing this. Feel free to reopen if needed.
