### ISSUE TITLE
Internationalization and admin editing (i18n_patterns compatibility)

### ISSUE THREAD

**Issue by PukeCloud** [idlesign/django-sitetree#148]
When you save TreeItem in admin interface and have current language different from language of Tree that this item belongs to - all the menus are rendered with current language prefix.

Example:
1. You have 2 menus for 2 languages - menu_ru and menu_en.
2. You change your language to 'ru' and open any item of 'menu_en'.
3. Save this item
4. All menu urls on site are rendered with wrong prefix.

**Comment by idlesign** [comment]
What's a `prefix` you've mention in p. 4, how do you define urls for your items?
Where do you activate a locale?

**Comment by PukeCloud** [comment]
> What's a prefix you've mention in p. 4

`prefix` is language prefix added by [django's i18n_patterns](https://docs.djangoproject.com/en/1.7/topics/i18n/translation/#django.conf.urls.i18n.i18n_patterns)
i.e. `/en/<path>/` for english `en` language

> how do you define urls for your items?

TreeItems affected by this "bug" have urls defined as patterns. TreeItems with raw urls are not affected. I supose that it has to do something with active translation during sitetree object being generated after saving TreeItem in admin interface.

> Where do you activate a locale?

It is activated on public pages of site via [django's set_language](https://docs.djangoproject.com/en/1.7/topics/i18n/translation/#the-set-language-redirect-view). So it's kept in user's cookies/session,

**Comment by idlesign** [comment]
> i18n_patterns

Thank you for the report. 
I'll check it this week.

**Comment by idlesign** [comment]
Please check out from `feat_i18n_patterns` branch to verify things work.

**Comment by PukeCloud** [comment]
Got `KeyError at <url> u'request'`

From traceback:
```
File "/usr/local/lib/python2.7/site-packages/sitetree/sitetreeapp.py" in url
  532.         lang = getattr(self._global_context['request'], 'LANGUAGE_CODE', '')
```

**Comment by idlesign** [comment]
Updated.

**Comment by PukeCloud** [comment]
Checked all the combinations of saving with different locales - everything works great.
Thank you for your work.

P.S.: I've noticed that suffix added to cache keys is not exactly the language, but can be a combination of two languages (i.e.`main_menu_ruen`). This happens when you save one menu, change locale and open another in admin interface. It doesn't seem to affect the work of application, but it seemed strange to me so I've decided to point it out.

**Comment by PukeCloud** [comment]
Oh sorry, I've checked submenus and seems like they don't work just like before. Yet `trunk` menu is rendered with right prefixes - submenus are not rendered at all.

**Comment by idlesign** [comment]
> is not exactly the language, but can be a combination of two languages
Yeah, that's tree alias plus current lang code.

> I've checked submenus and seems like they don't work just like before.
What are `submenus`? Can you also verify this behaviour is introduced in `feat_i18n_patterns` (i.e. not present in `master`)?

**Comment by PukeCloud** [comment]
> Yeah, that's tree alias plus current lang code.

Actually there are keys `main_menu_en` and something like `main_menu_ruru` or `main_menu_ruen`

> What are submenus?

`submenus` are child TreeItems of `trunk` items

> Can you also verify this behaviour is introduced in feat_i18n_patterns (i.e. not present in master)?

This behavious is in both branches. But there is a difference:  
When you save Item with wrong locale in `master` - you get that bug, but all the Tree and TreeItems for another language is ok.
In `feat_i18n_patterns` both menus are affected, yet all urls in `trunk` have right prefixes.

**Comment by idlesign** [comment]
Thank you. I'd reproduce this locally, and think what could be done.

**Comment by idlesign** [comment]
The latest change'll probably help, yet I'm not quite satisfied with the solution.

**Comment by PukeCloud** [comment]
Looks like everything works great:
1. All Items are rendered with correct prefix
2. All child menus and breadcrumbs are rendered as well

**Comment by MagisterLaporem** [comment]
Столкнулся с такой же ситуацией. Спасибо все вроде работает.

**Comment by idlesign** [comment]
I see. Will think how to optimize the solution on spare time.

**Comment by PukeCloud** [comment]
Any chance this gets into next release?

**Comment by idlesign** [comment]
All chances. Yet I'd probably come up with another solution in two days or so.

**Comment by idlesign** [comment]
You can try it now.

**Comment by idlesign** [comment]
Next release is planned in a week, if you can confirm the latest implementation solves the problem this fix will make it into the version.

**Comment by PukeCloud** [comment]
As much as I've tested - everything works as expected.

**Comment by idlesign** [comment]
Thank you. Merged.
