### ISSUE TITLE
python manage sitetree_resync_apps looks in wrong folders

### ISSUE THREAD

**Issue by acidjunk** [idlesign/django-sitetree#151]
I'm using a best practice for project structure:
http://stackoverflow.com/questions/22841764/best-practice-for-django-project-working-directory-structure

The installed apps look like this:
```'project.apps.staticpage',
    'project.apps.manage',
    'project.apps.accounts',
    'project.apps.customers'```

I created a sitetree.py in project/apps/customers and tried to load it in the DB:

No sitetrees found in project apps (searched in %app%/sitetrees.py).

Am I missing some sitetrees setting?

**Comment by idlesign** [comment]
> I created a sitetree.py in project/apps/customers and tried to load it in the DB

Is it `sitetree.py` or `sitetrees.py` as defaults?

**Comment by acidjunk** [comment]
I renamed it to sitetrees.py and it works like a charm now :)

FYI:
The docs mention sitetree.py
https://django-sitetree.readthedocs.org/en/latest/apps.html

**Comment by idlesign** [comment]
Thank you for this report. 
Fixed.
