### ISSUE TITLE
django 1.8 compatibility

### ISSUE THREAD

**Issue by reb00ter** [idlesign/django-sitetree#152]
just updated django to 1.8 and got error
Exception Type:	AttributeError
Exception Value:	'module' object has no attribute 'FilterExpression'
at
    {% sitetree_menu from "main" include "index" template "topmenu.html" %}
in the template

**Comment by idlesign** [comment]
Thank you for the report.
I'll look into it.

**Comment by idlesign** [comment]
Seems to be fixed. You can try out master branch now.

**Comment by idlesign** [comment]
Considered closed as of 1.4.

**Comment by thestick613** [comment]
kind of unrelated, but how do you apply
http://django-sitetree.readthedocs.org/en/latest/quickstart.html
on django 1.8, when the docs say that TEMPLATE_CONTEXT_PROCESSORS has been deprecated?

**Comment by idlesign** [comment]
@thestick613 Thank you for that question. Just updated the docs, so you can check those up.
