### ISSUE TITLE
Add kwargs to utils.item to allow passing custom fields

### ISSUE THREAD

**Issue by wengole** [idlesign/django-sitetree#154]
Hi,

I've overridden TreeItem with a custom model to add an Icon field. This all works well at run time, however I'm unable to add the icon in my ``sitetree.py`` file so that fresh installations have the correct icon.

I propose a simple fix would be adding a kwargs parameter to ``utils.item`` method that gets passed to ``get_tree_item_model()``. This way custom fields can be specified at "compile-time" and ``sitetree_resync_apps`` will add the menus exactly as required.

I can provide a pull request if you're interested?

**Comment by idlesign** [comment]
Hi,

Good idea. Waiting for a pull request with docs update.
