### ISSUE TITLE
Sitetree does not support items without a link

### ISSUE THREAD

**Issue by sturmf** [idlesign/django-sitetree#159]
I want to create the following menu.

* Plants
 * Vegetables
   * Apple
    * Peach

But I only want to have the Apple and the Peach to have a clickable link. Clicking on Plants should only reveal the lower menu entry Vegetables and clicking on Vegetables should finally reveal the Apple and Peach entries. 
It unfortunately seems such a menu layout is not supported?
Therefore this feature request.

**Comment by idlesign** [comment]
You can use custom templates and appropriate JS. E.g.: builtin Twitter Bootstrap templates behaves in a kind of similar manner.

**Comment by sturmf** [comment]
Thanks for the tip. I guess I change the template in that direction and match on the # sign. But why not just allow an item with a blank url?

**Comment by idlesign** [comment]
The main idea was that any item in a hierarchy should represent some accessible site realm: from pov of structurization/navigation it is best to have pages for various *Vegetables*. 
And `#` is widely used in cases with fancy menus requirements.

**Comment by idlesign** [comment]
Closing this. Feel free to reopen if needed.
