### ISSUE TITLE
dynamic sitetree - access_by_perms

### ISSUE THREAD

**Issue by waszi** [idlesign/django-sitetree#165]
I have tried to add access_by_perms to my dynamic sitetree but it is ignored. Test user wihout
'service.is_hosting_user' is still able to see menu item.

my app sitetrees.py:

```
from sitetree.utils import tree, item
from django.utils.translation import ugettext_lazy as _

sitetrees = (
    tree('dynamic', items=[
        item(
            _('FTP Accounts'),
            'ftp:index',
            access_loggedin=True,
            access_by_perms=['service.is_hosting_user'],
            alias='ftp_index',
            children=[
                item(_('Add'), 'ftp:add'),
                item(_('List'), 'ftp:index'),
                item(_('{{ obj }}'), 'ftp:edit obj.pk', in_menu=False, children=[
                    item('Access logs', 'ftp:logs obj.pk'),
                ]),
            ]
        ),
    ]),
)
```

**Comment by idlesign** [comment]
Thank you for the report. 
I'll try to reproduce it and see what could be done in a couple of days.

**Comment by idlesign** [comment]
You can now verify changes in bugfix/165 fixed the problem - https://github.com/idlesign/django-sitetree/commit/4fef97febe57639346d72994dd369f09526d0a17

**Comment by idlesign** [comment]
Consided closed by https://github.com/idlesign/django-sitetree/commit/b658509b39f6c8bf585ab7dbf2c383fdff3c52d1
