### ISSUE TITLE
Error: 'sitetree_menu' tag requires four arguments. E.g. {% sitetree_menu from "mytree" include "trunk,1,level3" %}.

### ISSUE THREAD

**Issue by stringsonfire** [idlesign/django-sitetree#168]
Just installed `sitetree` via `pip` (is that up to date?).

 I've made a tree and added this to my template:

    {% load sitetree %}
    {% sitetree_menu from "usermenu" %}

However, I get an `Error during template rendering` on `{% sitetree_menu from "usermenu" %}`:

    TemplateSyntaxError at /
    'sitetree_menu' tag requires four arguments. E.g. {% sitetree_menu from "mytree" include "trunk,1,level3" %}.

With vars:

    use_template	None
    tokens_num	3
    tokens	['sitetree_menu', 'from', '"usermenu"']

This has been raised as an [issue](https://github.com/idlesign/django-sitetree/issues/111) before.

`{% sitetree_tree from "usermenu" %}` works fine. I don't think `sitetree_menu` works the same way, so the docs are wrong: `Put ‘{% sitetree_menu from “maintree” %}’ into your template to render menu.`

**Comment by stringsonfire** [comment]
Yeah, the docs are wrong, should say something like {% sitetree_menu from "maintree" include "trunk" %}.

**Comment by idlesign** [comment]
Thank you fot the report. Docs fixed.
