### ISSUE TITLE
Request: Support for {% code %} content in menu

### ISSUE THREAD

**Issue by stringsonfire** [idlesign/django-sitetree#170]
I'm trying to build replacement menu for django-postman. Inbox has a count of unread messages in the nav, but this shouldn't appear if there are no new messages:

     <li>
        <a href="{% url 'postman:inbox' %}">
            &raquo;&nbsp;{% trans "Inbox" %}{% if unread_count %} <strong>({{ unread_count }})</strong>{% endif %}
        </a>
    </li>

Would it be possible to add functionality to use something like `Inbox {% if unread_count %} <strong>({{ unread_count }})</strong>{% endif %}` within the menu, instead of just template tags? I appreciate that I could set up the tag separately, but then that would have to be repeated on each page the menu is used.

**Comment by idlesign** [comment]
This could be achieved with the help of custom templates and tree hooks. You'll probably need some JS shyf if you want to update counter by long polling or websockets.

**Comment by idlesign** [comment]
Considered closed. Feel free to reopen si required.
