### ISSUE TITLE
Request: ID and Class Fields

### ISSUE THREAD

**Issue by stringsonfire** [idlesign/django-sitetree#171]
If you could set an ID and/or Class for an item to be output as part of that element, there'd be far more control than in doing so in a template, and it would be very easy to manipulate the results with javascript. What do you think?

**Comment by idlesign** [comment]
The common approach, as it established quite a time ago: if `alias`, `hint` and tree hooks are not enough for your purposes you can easily make a custom tree item model with all required fields.

**Comment by idlesign** [comment]
Considered closed. Feel free to reopen is required.
