### ISSUE TITLE
Could not parse the remainder: '“maintree”' from '“maintree”'

### ISSUE THREAD

**Issue by temrdm** [idlesign/django-sitetree#173]
Hello. That's the error when I paste ```{% sitetree_menu from “maintree” include "trunk" %}``` into my template. Sitetree "maintree" created in admin.
Django 1.8.4

**Comment by idlesign** [comment]
Hi, 

Try instead of `“` unicode symbols, use old plain ascii `"`.

**Comment by temrdm** [comment]
Oh, sorry. Thank you.

**Comment by temrdm** [comment]
Fix unicode symbols in docs ```http://django-sitetree.readthedocs.org/en/latest/quickstart.html#making-tree``. I am copy.

**Comment by idlesign** [comment]
Hm. It seems there's nothing to fix, as in source there are `"` (0022) everywhere I could see, not `“` (201c). It's probably RTD fault on rendering .rst.

**Comment by idlesign** [comment]
Considered closed.
