### ISSUE TITLE
Restricted tree elements are not visible and editable from admin

### ISSUE THREAD

**Issue by fallenflint** [idlesign/django-sitetree#175]
Hello.

Django-sitetree v. 1.4.0, mentioned bug makes unabled management of restricted "only for guests" tree elements.

**Comment by idlesign** [comment]
Hi,

Seems to be fixed (see #164) and will be available in next release. Meanwhile, you can verify `master` is working.

**Comment by fallenflint** [comment]
Great. I've searched, but haven't found. Thanks.
