### ISSUE TITLE
docs: How to build the site tree

### ISSUE THREAD

**Issue by guettli** [idlesign/django-sitetree#176]
First: Thank you for the great app. This is django menus done wright :-)

I would like to see a new chapter in the docs:

**How to create the site tree database items**

I see these ways:

  * sitetree_resync_apps
  * by hand: Django admin interface
  * dump/load
  * with migrations

Maybe there is even a fifth way to do it.

There should be a little note about the pro- cons
of each way.

**Comment by idlesign** [comment]
Thank you.

Basically any way you add items into DB will do. And there are neither pros no cons in that - it's pure data, so it could even be an SQL-query. You just pick an approach that suits well you current task.

**Comment by guettli** [comment]
I know that, but new comers don't. It was just a hint that the docs could be improved. But it is not very important.

**Comment by idlesign** [comment]
Pull requests with docs improvements are welcome.
By now let's consider this issue closed.
