### ISSUE TITLE
Django 1.9

### ISSUE THREAD

**Issue by soulraven** [idlesign/django-sitetree#179]
Hello can you make the migration also to django 1.9

i get this error when i do manage.py test

sitetree/utils.py:4: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

also will be good to have a 1.9 compatible version

**Comment by idlesign** [comment]
Hi,

Thanks for the report, we'll see what could be done in a couple of days.

**Comment by idlesign** [comment]
Some stuff for 1.9 is already in master. That includes `import_module` issue. 
New version will be released in a couple of weeks.

Closing this, feel free to reopen if required.

**Comment by soulraven** [comment]
i have problems when i try to edit a menu from admin section, i get this error:

```
Page not found (404)
Request Method:	GET
Request URL:	http://domain/admin/sitetree/tree/1/change/item_38/change/
Raised by:	django.contrib.admin.options.change_view
Site Tree object with primary key u'1/change/item_38' does not exist.
```

**Comment by idlesign** [comment]
Is it 1.8? If so please try code from `master`, there was similar issue fixed some time ago.
