### ISSUE TITLE
Cannot edit Tree Items that are "not in tree" in django admin

### ISSUE THREAD

**Issue by danithaca** [idlesign/django-sitetree#180]
When I mark a tree item in django admin as not "Show In Site Tree" or "Hidden", the item is not accessible again from django admin. This seems to be counter-intuitive, where users should be able to go to that item and mark it as "show in site tree" again. But now it's just not able to.

**Comment by idlesign** [comment]
Seems to be fixed by #169. 
You can verify it in `master` branch.

**Comment by danithaca** [comment]
confirmed. this issue was fixed in master branch.
