### ISSUE TITLE
NoReverseMatch with custom Models

### ISSUE THREAD

**Issue by jiangrzh** [idlesign/django-sitetree#181]
I catch a NoReverseMatch error while using a custom model in django version 1.8
```python
NoReverseMatch at /admin/TreeTest/mytree/1/item_add/
Reverse for 'treetest_mytree_changelist' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

**Comment by idlesign** [comment]
sitetree version?

**Comment by jiangrzh** [comment]
V1.5.0

 

发件人: Igor Starikov [mailto:notifications@github.com] 
发送时间: 2015年11月25日 20:49
收件人: idlesign/django-sitetree <django-sitetree@noreply.github.com>
抄送: Jiangrz <zfjrz@189.cn>
主题: Re: [django-sitetree] NoReverseMatch with custom Models (#181)

 

sitetree version?

—
Reply to this email directly or view it on GitHub <https://github.com/idlesign/django-sitetree/issues/181#issuecomment-159598615> .  <https://github.com/notifications/beacon/ADjaBKokUXWLnDDkXcoviVVS2YmC9D8Sks5pJaXIgaJpZM4Go5uV.gif> 



---
Avast 防毒软件已对此电子邮件执行病毒检查。
https://www.avast.com/antivirus

**Comment by idlesign** [comment]
Thank you for the report, I'd try to look into it this week.

**Comment by idlesign** [comment]
I'm unable to reproduce this behavior in 1.8.
I've made some changes for 1.9 (wich had similar error messages) in master, you can try that out.
If it won't do, please show your custom model and app code.

**Comment by jiangrzh** [comment]
Thank you, 
I found the problem is my app's name  contain upper-case letter like "TreeTest", and the get_model_url_name function will trans them to lower case. should i need to rename my app with all lower case letters ?

**Comment by idlesign** [comment]
Since your app is a module, module naming conventions from PEP8 apply just fine: https://www.python.org/dev/peps/pep-0008/#id32

Considered closed, feel free to reopen at will.
