### ISSUE TITLE
"Add Site Tree Item" results in 404 Error

### ISSUE THREAD

**Issue by radiovisual** [idlesign/django-sitetree#187]
Hey there, I have just installed django-sitetree using `pip install django-sitetree`, and I followed the instructions [here](http://django-sitetree.readthedocs.org/en/latest/quickstart.html). 

I was able to see the "Site Trees" in the Django Admin Section, and I was also able to add a Title and an Alias, but as soon as I click on the button `+ ADD SITE TREE ITEM`, I get the following error:

<pre>
Page not found (404)
Request Method:	GET
Request URL:	http://localhost:8000/admin/sitetree/tree/2/change/item_add/change/
Raised by:	django.contrib.admin.options.change_view
Site Tree object with primary key u'2/change/item_add' does not exist.
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
</pre>

*I am using Django 1.9, and django-sitetree 1.5.0*

**Comment by idlesign** [comment]
Thats 1.9 related issue. You can check out `master` branch to verify this issue is fixed.
Release is planned this year %)

**Comment by radiovisual** [comment]
@idlesign, ok, thanks. I will check out the `master` branch and I look forward to the new release! :sunglasses:

**Comment by idlesign** [comment]
1.5.1 is available at PyPI.
Closing this one.

**Comment by radiovisual** [comment]
:+1:
