### ISSUE TITLE
'No migrations to apply' during app setup

### ISSUE THREAD

**Issue by radiovisual** [idlesign/django-sitetree#188]
I am not sure if this problem is related to my [404 problem](https://github.com/idlesign/django-sitetree/issues/187). I am experiencing these issues at the same time, but they feel like separate issues, so I am opening two tickets. 

While following the setup instructions [in the documentation](http://django-sitetree.readthedocs.org/en/latest/quickstart.html), step #4 asks us to run the following:

```
Run ./manage.py syncdb to install sitetree tables into database (./manage.py migrate for Django 1.7+)
```

So after running `./manage.py migrate`, I get the following output:

```
?: (urls.W002) Your URL pattern '^/$' [name='sitetree_treeitem_changelist'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
Operations to perform:
  Apply all migrations: sitetree, sessions, admin, auth, djangoapp, contenttypes
Running migrations:
  No migrations to apply.
```

The highlight here is that is it says there are no migrations to apply, but since database migrations is listed as a specific requirement during the install process, it felt odd that nothing happened during the migrations. 

**So is it normal for no migrations to take place? Or is something wrong?**

Thanks!

*I am using Django 1.9, and django-sitetree 1.5.0*

**Comment by idlesign** [comment]
Please verify `sitetree` is in INSTALLED_APPS.

**Comment by radiovisual** [comment]
@idlesign `sitetree` is in my `INSTALLED_APPS`. I was able to make a `Site Tree` entry in the admin, which means the app was recognized by Django, but there just weren't any migrations to apply. 


Here is my INSTALLED_APPS:
```python
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webpages',
    'ckeditor',
    'ckeditor_uploader',
    'sitetree',
]
```

**Comment by idlesign** [comment]
If you add sitetrees without any problems, it basically means that your DB is ready (most probably all migrations were applied before).
Closing this one as resolved.
