### ISSUE TITLE
sitetrees_reset typo

### ISSUE THREAD

**Issue by pczerkas** [idlesign/django-sitetree#191]
Hi, I think there is a typo in https://github.com/idlesign/django-sitetree/blob/f9b8dca1a78c2e5eba363b6924446230cf7be470/sitetree/sitetreeapp.py#L287
Shouldn't this line read:
cache.set('sitetrees_reset', True)
?

Regards,
Przemek

**Comment by idlesign** [comment]
Hi,

Exactly! Thank you for the report.

**Comment by idlesign** [comment]
Fix landed in master.
