### ISSUE TITLE
Caching logic performance

### ISSUE THREAD

**Issue by seanbell** [idlesign/django-sitetree#194]
I think there might be a logic error here: https://github.com/idlesign/django-sitetree/blob/master/sitetree/sitetreeapp.py#L293

I think the line `cache.get('sitetrees_reset') and self.empty()` should use `or` instead of `and`.

If `'sitetrees_reset'` is in the cache, then `self.empty()` does _not_ get called.  If `'sitetrees_reset'` is not in the cache, then `self.empty()` _does_ get called.

I think that's the opposite of the intended behavior?  Apologies if I'm wrong.

I've been using your library and it is great -- thanks for releasing/maintaining it!  I noticed lots of cache calls which add up (~20 calls per page) and started reviewing the code to see whether there is a bug in the caching logic.

**Comment by idlesign** [comment]
Can see no fault in the line: that's a short circuit, reads as follows - if there's a reset hint in cache, do empty cache. The hint could be set with `cache.reset()` (which was fixed recently #191) - this facilitates cache invalidation from within different processes.

```
I noticed lots of cache calls which add up (~20 calls per page) [...]
```
Do you mean mere method calls or something else?

**Comment by seanbell** [comment]
Aah sorry for wasting your time; yes I see that the short circuit is correct with `and`.

Yeah, I mean the method calls.  I'm not sure if it is the design that prevents this, but I wonder if there is some way to avoid making 20 `cache.get` calls per page render.  It seems to me like there should be a way of doing it with 1-2 `cache.get` calls (e.g. with some middleware that saves a variable in the context).

![image](https://cloud.githubusercontent.com/assets/1844189/12933591/e9862a4e-cf56-11e5-8a4e-e7da3708388e.png)

**Comment by seanbell** [comment]
The calls are all initiated from `{{ item.title_resolved }}`

![image](https://cloud.githubusercontent.com/assets/1844189/12933808/2c86e346-cf58-11e5-9f84-0c278511e8c6.png)

**Comment by idlesign** [comment]
```
I wonder if there is some way to avoid making 20 cache.get [...]
```
Hypothetically. Why bother, do you think those calls are a bottleneck of you app?

**Comment by seanbell** [comment]
They add up to 44ms, which can be longer than the database queries for my pages.  I probably won't look into trying to optimize this.

**Comment by idlesign** [comment]
I see. I'll leave it open as a reminder on what to improve.

**Comment by idlesign** [comment]
Cache calls number is reduced in `master`. 
Should be fine for now, yet, further imporvements may follow.
Thank you for the report. Closing this one
