### ISSUE TITLE
RemovedInDjango110Warning

### ISSUE THREAD

**Issue by leotop** [idlesign/django-sitetree#202]
sitetree/templatetags/sitetree.py:306: RemovedInDjango110Warning: render() must be called with a dict, not a RequestContext.
`  content = get_template(use_template).render(context)`

/sitetree/sitetreeapp.py:803: RemovedInDjango110Warning: render() must be called with a dict, not a RequestContext.
`  return my_template.render(context)`

**Comment by idlesign** [comment]
That one is addressed in #201. 
Closing as duplicate.

**Comment by leotop** [comment]
comment move to #201
