### ISSUE TITLE
AttributeError: "'RequestContext' object has no attribute 'current_app'"

### ISSUE THREAD

**Issue by philsheard** [idlesign/django-sitetree#204]
Hi Igor, thanks for the package.

I'm just setting up a new site using Django 1.10 and got this error, both within the Admin section for editing a tree, and when including the tags within the templates.

I'm guessing it's a change brought in by Django 1.10, as I have a 1.9 app running fine with the current version on PyPi.

Let me know if I can help debug or answer further questions.

**Comment by gb119** [comment]
The latest version off github fixes that problem (but I had a further breakage with adding root items).
pip install --upgrade git+{{ github git clone URL }} is your firend here.

**Comment by idlesign** [comment]
@philsheard Hi! This one is related to Django 1.10 indeed and it should be fixed in master.  You can either try it right from there or just wait for sitetree release (presumably a week or so).

**Comment by philsheard** [comment]
@idlesign Thanks for the update, that's great. I'll go from master then.

**Comment by idlesign** [comment]
Should be fixed in https://github.com/idlesign/django-sitetree/commit/ffae9edb63dc1deb8fbe76f32c09df4bd2445ac5
Closing this one. Thank you for the report.
