### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by bnisevic** [idlesign/django-sitetree#206]
I get this after Django upgrade to 1.10:

`'RequestContext' object has no attribute 'current_app'`

`site-packages/sitetree/sitetreeapp.py in current_app_is_admin, line 415`

**Comment by bnisevic** [comment]
Sry, I see that this is fixed in the master:
https://github.com/idlesign/django-sitetree/blob/master/sitetree/sitetreeapp.py#L419

Function is completely different than  in v1.5.1. So, when will you make a new release?

**Comment by idlesign** [comment]
Release is due in a week or so. Meanwhile you may want to verify that the code from `master` works for you.
Closing as dupe #201 #204
