### ISSUE TITLE
Need help with Bootstrap template (maybe a problem with sitetree_items)

### ISSUE THREAD

**Issue by TitanFighter** [idlesign/django-sitetree#207]
According to the docs, initially I used
`{% sitetree_menu from "maintree" include "trunk,topmenu" %}` and everythin worked ok.

Then I tried to work with `menu_bootstrap3*.html` templates, but when I copy-paste code to my 
`base.html`, nothing happens. It looks like `sitetree_items` in `{% for item in sitetree_items %}` is empty.

For a test I made such menu structure:
```
MySite     
Account       
  |— SignUp       
      |— test  
  |— LogIn              
  |— Social        
  |— Emails    
```

I use Django 1.10, Python 3.5.1, Ubuntu 16.04.

Would appreciate any advice.
Thanks.

**Comment by TitanFighter** [comment]
It seems that I found where the problem was.
It was needed to:
1. Create a file `menu.html` at `myproject/templates/sitetree/`
2. Copy to this file (menu.html) the code from `menu_bootstrap3.html`
3. In `myproject/templates/base.html` must be `{% sitetree_menu from "maintree" include "trunk,topmenu" %}`

Is it how everything should be?

**Comment by idlesign** [comment]
> It was needed to add template "sitetree/menu_bootstrap3.html" 

Indeed. This is mentioned in http://django-sitetree.readthedocs.io/en/latest/tags.html close to the beginning.
