### ISSUE TITLE
__init__() got an unexpected keyword argument 'current_app'

### ISSUE THREAD

**Issue by bnisevic** [idlesign/django-sitetree#208]
`TypeError at /en/admin/sitetree/tree/5/change/item_add/`

`__init__() got an unexpected keyword argument 'current_app'`

lib/python3.5/site-packages/sitetree/fields.py in _build_choices, line 40

Similar to what I had before, but I see that current_app is used in the master also.

**Comment by idlesign** [comment]
There's no `__init__()` call in `_build_choices()` on line 40. 
Please verify your `master` clone is up-to-date.

**Comment by bnisevic** [comment]
I'm sorry, it works with master. Thank you.
