### ISSUE TITLE
Is it possible to make one button with 2 links?

### ISSUE THREAD

**Issue by TitanFighter** [idlesign/django-sitetree#210]
Hi Igor.

Could you pls advice me anything on the next issue:
I want to give my users such option as a custom address creation, such as `site.com/username`, but do not want to force them to do this, so some addresses may look like `site.com/id12345`. In admin, in Site Tree section, I want to create an item, something like 'My page', but as you see, there could be 2 kinds of url. I tried to add something like `profiles_user:profiles_home user.username | profiles_user:profiles_home user.pk` but no luck :).

Currently I have:

    # root urls.py
    urlpatterns = [
       url(r'^((?P<user_id>[i][d]\d+)|(?P<username>[\w.+-]+))/', include('profiles.urls', namespace='profiles_user')),
    
    # profiles/urls.py
    from django.conf.urls import url
    from . import views
    
    urlpatterns = [
        url(r'^$', views.profiles_home, name='profiles_home'),
    ]
    
    # profiles/views.py
    def profiles_home(request, user_id=None, username=None):
        if user_id:
            user_id = int(user_id.replace('id', ''))
            user = get_object_or_404(UserProfile, pk=user_id)
        else:
            user = get_object_or_404(UserProfile, username=username)
        return render(request, 'profiles/profiles_home.html', {'profile_user': user})

Thank you.

**Comment by idlesign** [comment]
Hi,

I'd rather come up with a single regexp group within url instead of separate `user_id` and `username`, so that `profiles_home` works with a single param.

**Comment by TitanFighter** [comment]
Fixed by adding a new field `user_url` into `models.py`, and in `SiteTree` in the `url` field put `profiles_user:profiles_home user.user_url`
