### ISSUE TITLE
sitetree_resync_apps ImportError

### ISSUE THREAD

**Issue by mauzil** [idlesign/django-sitetree#211]
Goodmorning.
My name's Mauro and I write from Parma Italy.
I'm trying to use sitetree with Django 1.10.1.
I define a tree menu in my application named polls.

When I run sitetree_resync_apps polls Django tell me:
ImportError: no module named PollsConfig.

I get the same beavihour with Django 1.9.9

Do you have any idea about this message?

Thanks
  MZ

**Comment by mauzil** [comment]
Hi all.
I solved the matter.
in the django tutorial https://docs.djangoproject.com/en/1.10/intro/tutorial02/ I have to add my application putting 'polls.apps.PollsConfig' in top of INSTALLED_APPS.

I try to put 'polls' at end of INSTALLED_APPS list and sitetree_resync_app works well.

Also Django site works ok.

**Comment by idlesign** [comment]
Hi, Mauro,

Yes, you either add into `INSTALLED_APPS`  `poll` (that is the name of your app), or `polls.apps.PollsConfig` (that is application config `PollsConfig` in module `apps` of you `polls` app).
