### ISSUE TITLE
Tree is not iterable 

### ISSUE THREAD

**Issue by mauzil** [idlesign/django-sitetree#212]
Hi all.
I'm trying sitetree_resync_apps, but the command stops at line 48 of sitetree_resync_apps.py with the message

TypeError: 'Tree' object is not iterable

MZ

**Comment by idlesign** [comment]
Hi,

What do you have in `sitetrees.py`?

**Comment by mauzil** [comment]
Hi,
Thanks for the question.
Looking inside my sitetrees.py, i have not declared the tree in the right way.
Some commas missing.

Now it works.

Thanks
  MZ
