### ISSUE TITLE
sitetree_resync_apps requires you to specify an app

### ISSUE THREAD

**Issue by markkennedy** [idlesign/django-sitetree#214]
From the docs, it appears you should be able to run this command and have all sitetrees in all apps resync:

`python manage.py sitetree_resync_apps`

However, when I run that command without an app argument, I get the following error:

```
usage: manage.py sitetree_resync_apps [-h] [--version] [-v {0,1,2,3}]
                                      [--settings SETTINGS]
                                      [--pythonpath PYTHONPATH] [--traceback]
                                      [--no-color] [--database DATABASE]
                                      [args [args ...]] app [app ...]
manage.py sitetree_resync_apps: error: too few arguments
```

The solution seems to be to to make the argument optional by using the `*` instead of the `+` in `nargs`, e.g.:
```python
        parser.add_argument('args', metavar='app', nargs='*', help='Application names.')
```

**Comment by idlesign** [comment]
Thank you for the report.
This issue was fixed in #213. You can try it out in `master`.
Considered closed. Feel free to reopen if needed.
