### ISSUE TITLE
Ошибка перевода

### ISSUE THREAD

**Issue by archonoff** [idlesign/django-sitetree#215]
Привет
А можно как-то исправить [вот тут](http://clip2net.com/clip/m0/3d134-clip-14kb.png) невнятное "Дерева сайта" на корректное "Дерево сайта" или "Деревья сайта"?
А-то эта "дерева сайта" глаз жутко мозолит...

**Comment by idlesign** [comment]
Привет.

Можно, только там нечего исправлять: `дерева` (с ударением на последний слог) - это имеющая место быть форма множественного числа. Вариант "Деревья сайта" в моём личном рейтинге проиграл данной акцентированной форме.

**Comment by archonoff** [comment]
Глянул на грамоте, действительно "имеет место быть" такая форма, с пометкой "устаревшая". Ладно, дело в общем-то твое.

**Comment by idlesign** [comment]
Закрываю.
