### ISSUE TITLE
Dynamic object list in menu

### ISSUE THREAD

**Issue by friendka** [idlesign/django-sitetree#216]
/* en version is below */

Доброго времени! Нашел это приложение, но на первый взгляд не понятно, возможно ли решить мою задачу с помощью него. Предполагаю, что задача популярна и возможно стоит более детально осветить подобный кейз.

Есть два приложения. Первое - SimplePages, где есть только модель SimplePage. Второе - InformationPortal, где есть две модели - Category и Article.

Для приложения SimplePages заведено 15 объектов. Для InformationPortal - 10 Category и 500 Article, раскиданных по Category.

Нужно создать такое меню:

Home (/)
---- SimplePage3Title (/page3slug/)
---- SimplePage8Title (/page8slug/)
---- SimplePage1Title (/page1slug/)
---- InformationPortalTitle (/information_app_url/)
----  ---- Category1Title (/information_app_url/category1slug/)
----  ---- Category2Title (/information_app_url/category2slug/)
----  ---- Category5Title (/information_app_url/category2slug/)
---- SimplePage4Title (/page4slug/)
---- Article499Title (/information_app_url/category10slug/article499slug/)
---- SimplePage8Title (/page8slug/)

Говоря о реализации этой задачи, мне видится такой подход (с учетом первого знакомства с sitetree). Редактор сайта добавляет в нужной последовательности все объекты SimplePages с 'URL как шаблон' вида 'page_detail page3slug', добавляет элемент меню InformationPortalTitle с 'URL как шаблон' вида 'category_list', добавляет элемент меню Article499Title c 'URL как шаблон' вида 'article_detail category10slug article499slug'.

Поскольку Category может быть достаточно большое количество, хотелось бы их прикреплять дочками к элементу меню InformationPortalTitle в автоматическом режиме на основе имеющихся у Category полей (boolean 'should_show_in_menu' и integer 'menu_sort_order')

Здесь и возникает затык. Чтобы прояснить дальнейшие действия и задаю вопрос. Так понимаю, нужно создать одноуровневое дерево InformationPortalTree с списком Category в information_app/sitetrees.py (а потом его сгенерировать sitetree_resync_apps information_app) и динамическое дерево, в которое будет включено дерево из админки (к элементу InformationPortalTitle которого будет прикрепляться дерево InformationPortalTree)?

И второй вопрос. Чтобы не назначать элементам SimplePageN заголовок, а брать его из самого объекта, необходимо модели SimplePage тоже добавлять параметры сортировки и метку видимости, а django-sitetree использовать только в исходниках для генерации меню, иных вариантов нет? 

----------------------------------------------------------------------

Good time! I found this app, but at first glance it is not clear whether it is possible to solve my problem. I assume that the problem is popular and might be worth more in detail to illuminate such case.

Suppose i have two applications. SimplePages, where there is only one model SimplePage. InformationPortal, where there are two models - Category and Article.

15 objects for SimplePages app. For InformationPortal app - 10 Category and 500 Article objects.

I need to create such menu:

Home (/)
---- SimplePage3Title (/ page3slug /)
---- SimplePage8Title (/ page8slug /)
---- SimplePage1Title (/ page1slug /)
---- InformationPortalTitle (/ information_app_url /)
---- ---- Category1Title (/ information_app_url / category1slug /)
---- ---- Category2Title (/ information_app_url / category2slug /)
---- ---- Category5Title (/ information_app_url / category2slug /)
---- SimplePage4Title (/ page4slug /)
---- Article499Title (/ information_app_url / category10slug / article499slug /)
---- SimplePage8Title (/ page8slug /)

Speaking about the implementation of this task, I see this approach (based on first acquaintance with sitetree). Site editor adds the correct sequence objects of SimplePages with 'URL as a template' 'page_detail page3slug', adds InformationPortalTitle menu item 'URL as a template' 'category_list', adds a menu item Article499Title 'URL as a template' 'article_detail category10slug article499slug '.

Since there may be a lot of Category objects, I would like to attach some of them InformationPortalTitle menu item automatically based on existing Category fields (boolean 'should_show_in_menu' and integer 'menu_sort_order')

To clarify the next steps i ask this question. Now i thinsk that i should: 1) create base tree in admin 2) create a single-level tree InformationPortalTree with Category objects in file information_app/sitetrees.py 3) create dynamic tree, which will include main tree from first step with attached menu from second step to InformationPortalTitle item from first tree?

And the second question. Is there any way to display SimplePageN title from corresponding object, but not to write it with sitetree app (DRY)?

**Comment by idlesign** [comment]
Hi,

Since site stucture tends to be dynamic, I'd rather use dymanic sitetrees from the very beginning. In that case syncing to DB is not a must. See dynamic tree generation in pythonz for example:  https://github.com/idlesign/pythonz/blob/master/apps/realms.py#L131

If you have static parts of menu, that should be configured by user from admin, you certainly can create a static base menu, and attach to one of its nodes the dynamic one. Or you can have two or more trees and address them from your templates.

But both from the perfomance and UX point of you'd better have a static menu with finite number items (those could be both supplied by a user or added/remove automatically, say on setting `should_show_in_menu` flag).

Common approach to denote a group of objects in sitetree is to describe it by a single sitetree item, having `URL as a pattern` and addressing object attribute in item's title with Django template variable notation `{{ obj.attr }}`. So, for example, that `Article {{ article.title }}` (`articles:details article.id`) would virtually describe any article.

Having in mind the above said I'd describe you site in the following sitetree items:

```
Home (/)
---- Page {{ page.title }} (simple_pages:details page.slug)
---- Categories (categories:listing)
---- ---- Category {{category.title}} (categories::details category.slug)
---- Article {{ article.title }} (articles::details category.slug article.slug)
```

Hope that clears things a little.

**Comment by friendka** [comment]
Thank you for support, but one more thing.

Am i right, that if editor wants to display all 10 Page items in menu, he should add 10 items to sitetree? Don't understand the way {{ obj.attr }} works

I made demo project with some data

[treedemo.zip](https://github.com/idlesign/django-sitetree/files/559912/treedemo.zip)

PS after logging in to http://pythonz.net/ 'log in' button doesn't dissapear at homepage

**Comment by idlesign** [comment]
Generally, yes, `{{ obj.attr }}` won't help you if you want to have all the items in a menu or in a site tree. It helps though in composing breadcrumbs navigation.

Your choices are: 1. put site tree items in DB (manually or with automatic triggering, as e.g. python.org did — https://github.com/python/pythondotorg); 2. compose in-memory dynamic tree (and recompose it on some signal or whatever); 3. reconsider the idea of putting too manu items in menu.

On pythonz: yes, there's some caching issue. You can file it here — https://github.com/idlesign/pythonz/issues or even resolve it if you will.
