### ISSUE TITLE
how to restrict menu item for django superuser

### ISSUE THREAD

**Issue by githingeorge** [idlesign/django-sitetree#217]

**Comment by idlesign** [comment]
Superuser named so not by chance.

**Comment by githingeorge** [comment]
Soory i didn't get you...for eample how to restrict below menu item so that only superuser sees it
```
item(
                    'Settings',
                    'admin:index',
                    in_menu=True,
                    in_sitetree=True,
                    access_loggedin=True,
                    icon_class="indent",
                ),
```

**Comment by idlesign** [comment]
There is no such an option out-of-box. You can use `access_permissions`, or a custom tree item model, or another menu (rendered only for superusers).

**Comment by acidjunk** [comment]
A possible workaround:
try to find a permission which you normally only give to an admin (e.g. delete user functionality) and use that to show the admin menu item when needed:

`item('Admin', 'admin:index', access_loggedin=True, in_menu=True, access_by_perms='auth.delete_user'),`

**Comment by idlesign** [comment]
Closing this one as resolved.
