### ISSUE TITLE
two items with different parents but same url results in only first having is_current set

### ISSUE THREAD

**Issue by simongartz** [idlesign/django-sitetree#219]
Hi!

I noticed that only the first item with same url are marked is_current. Is that by design or is it possible to achieve such structure in another way?

menu is as follows:

root
---- popular categories
-------- action - url /action/
-------- drama - url /drama/
---- all categories
-------- action - url /action/
-------- cartoon - url /cartoon/
-------- documentary - url /documentary/
-------- drama - url /drama/

If I go to /drama/ only the first drama item is_current is True.

**Comment by idlesign** [comment]
Hi,

Yes there is only one item in tree that is considered current, otherwise it would be not only imposible to build breadcrumbs, but also somewhat misleading if a user will see, say, several menu items as current. Yet, two separate trees trick will probably work.

**Comment by simongartz** [comment]
Good point, we don't use breadcrumbs so I guess we have not notice that kind of problem.

Thanks for the answer!
