### ISSUE TITLE
Странная ошибка рендеринга шаблона

### ISSUE THREAD

**Issue by archonoff** [idlesign/django-sitetree#220]
Привет

Не уверен, баг ли это django-sitetree, или это я накосячил, но я все же надеюсь на ответ.

В общем я тут словил странный баг: при заходе в админку,в редактирование конкретного дерева, вываливается исключение рендеринга шаблона, выглядит оно: [примерно так](http://clip2net.com/clip/m85056/09ab9-clip-192kb.jpg)

Причем зависит оно не от кода, а от базы. Я поясню: сначала я разрабатывал сайт с сервером БД на внутреннем корпоративном сервере, где все было хорошо, потом перенес его на vps (с помощью dumpdata-loaddata) и вскоре заметил этот эксепшен. К сожалению я не могу его точно связать с переносом, потому что перенес базу я в четверг, а ошибку заметил только сегодня, и за это время манагеры могли туда что-то добавить.

Но на данный момент ситуация такова, что не меняя код, а просто переключая базу, к которой подключается приложение, это бага или появляется, или исчезает.

Может быть ты, как автор, сможешь быстро догадаться, в какую сторону мне копать, чтобы починить это?

**Comment by idlesign** [comment]
Привет.

Я бы посмотрел нет ли чего подозрительного в таблице с элементами деревьев `TreeItem` — что там за значения в полях.

**Comment by archonoff** [comment]
@idlesign да, это было первое, что я сделал. Но на мой взгляд ничего подозрительного там нет [http://clip2net.com/clip/m85056/221e5-clip-158kb.png](http://clip2net.com/clip/m85056/221e5-clip-158kb.png)
То есть других гипотез, кроме той, что в базу что-то кривое внесли, нету?

**Comment by archonoff** [comment]
@idlesign 
Во-первых, я удалил свой предыдущий комментарий, все равно я там приложил неправильный скриншот=)
А во-вторых, я избавился от исключения, но похоже это действительно баг django-sitetree. Дело было в том, что в поле URL при поставленной галке «URL как шаблон» вписали такое `contentpages:page media` и проблема именно в слове media, т.к. django-sitetree нашел не то, что было нужно, из-за чего и вылетало исключение. Так что когда я заменил media на mass-media все пришло в норму. Тем не менее потенциально остается опасность, что слово media будет вписано опять.

**Comment by idlesign** [comment]
То есть, как и предполагалось, ошибка была в заполнении поля. Хорошо.

> [...] т.к. django-sitetree нашел не то, что было нужно, из-за чего и вылетало исключение [...]

Я бы не торопился: думаю, что `sitetree` нашёл-таки и то, что нашёл, честно подставил. В шаблон в переменной `media` приходит указанный в ошибке html.

Вообще для административной части отключена интерпретация параметров для URL, странно, что она производится. Родная админка используется или какая-то модификация? Какая версия Django?

**Comment by archonoff** [comment]
@idlesign 
Джанга 1.10.2, админка стандартная. Из "кастомизаций" у меня только перевод с помощью django-modeltranslation (делал [как написано в доках](http://django-sitetree.readthedocs.io/en/latest/thirdparty.html#django-modeltranslation))

> Вообще для административной части отключена интерпретация параметров для URL
А как она определяется? Дело в том, что у меня используется i18n_patterns и админка находится в частности по /ru/admin, а не стандартному /admin. Может быть из-за этого проблема?

**Comment by idlesign** [comment]
Определяется в методе current_app_is_admin(). 
Нужно будет удостовериться, что она вообще используется. На недели постараюсь поглядеть, что там можно предпринять.

**Comment by idlesign** [comment]
Пока не получается заняться задачей, но я помню про неё.

**Comment by idlesign** [comment]
Наконец добрался до задачи.

Пожалуй, тут не будет общего надёжного решения, которое можно было бы применить на уровне самого приложения: мы никак не сможем достоверно знать, какие переменные шаблона могут использоваться в URL, а какие нет.

Вообще, вряд ли можно конечному пользователю давать возможность напрямую рулить меню, но если других вариантов нет, то, наверное, лучшее, что можно придумать — это использовать свою модификацию поля URL, которая будет при валидации проверять наличие тех или иных переменных в этом поле и не давать сохранить элементы дерева, содержащие запрещённые слова.

**Comment by archonoff** [comment]
@idlesign
Спасибо за анализ проблемы.

**Comment by idlesign** [comment]
Закрываю.
