### ISSUE TITLE
Problem with manifest file?

### ISSUE THREAD

**Issue by 7wonders** [idlesign/django-sitetree#222]
Installed latest from master with pip install git+git://github.com/idlesign/django-sitetree.git@master and a whole bunch of directories were missing. Swapped out the manifest .py to * to include everything recursively just to test and then the directories are included as  expected.

**Comment by idlesign** [comment]
Thank you for the report.
It might be wheel-related. I'll check eventually.

**Comment by idlesign** [comment]
Seems to be broken by pypa/setuptools#764 since setuptools v28.5.0

**Comment by idlesign** [comment]
@7wonders Should be fixed.

**Comment by idlesign** [comment]
Closing this one as resolved in 1.7.0.
