### ISSUE TITLE
Release 1.6.1 or 1.7?

### ISSUE THREAD

**Issue by acidjunk** [idlesign/django-sitetree#223]
When using the pip version with Django 1.10 the management command sitetree_resync_apps doens't work (without an app name). But installing django-sitetree straight from github (e.g. -e git+https://github.com/idlesign/django-sitetree.git#egg=django-sitetree) yields a working install. Can you release a new version?

**Comment by idlesign** [comment]
Related to #222
Release is due in two-three days.

**Comment by idlesign** [comment]
This will be delayed by #225, as `master` is not ready for it yet.
Planning to finish it this week. Sorry for inconvenience.

**Comment by idlesign** [comment]
1.7.0 just released, you may try it.

**Comment by idlesign** [comment]
Closing this one as resolved.
