### ISSUE TITLE
Help with internationalization

### ISSUE THREAD

**Issue by pitervergara** [idlesign/django-sitetree#227]
I am trying to use the internationalization feature, but my translated items are not showing up.
I have a tree called _maintree_, which is has english titles and wroks ok. I have a second tree called _maintree_pt-br_, this one does not work.

On my 'main' urls.py (the next to my settings.py) I have:
```python
 from sitetree.sitetreeapp import register_i18n_trees
 register_i18n_trees(['maintree', ])
```

This is how I'm using on my templates:

```html
<!DOCTYPE html>
<html lang="en">
{% load sitetree %}
...
<h1 class="page-header">{% sitetree_page_title from "maintree" %}</h1>
```

On the templates where I expect to see the pt-br version of the page title, I have printed the language code and I see it's set to pt-br.

Django template:
```html
{% get_current_language as LANGUAGE_CODE %}
<!-- Current language is {{LANGUAGE_CODE}} -->
```
Rendered HTML:
```html
<!-- Current language is pt-br -->
```

I did not found any issues about internationalization, so I assume I'm missing something. Can anyone help me?

**Comment by idlesign** [comment]
Please show your trees and tree items.
I'll try to reproduce the issue in a couple of days.

**Comment by pitervergara** [comment]
Hi, thanks for your attention
Here is my _sitetreedump_ output: https://gist.github.com/pitervergara/fc7fe531f746f8df4f465a4ae94bd593

**Comment by idlesign** [comment]
Please try to omit ``-br`` from tree alias, let it be just ``pt`` and give it another try.

**Comment by pitervergara** [comment]
Yes. It does work. Thanks!

This solves my particular issue, as I only have to use _Brazilian Portuguese_ and therefore I don't need to distinguish _pt_ from _pt-br_.

---
I now that you pointed, I see that _resolve_tree_i18n_alias_ splits the language code and uses only first index. 

I believe that this is the list of language codes used in django and there are a few others which also have a hyphen, so I think this might cause issues with these other language variations too.

Use only the first part of the language code seems to be "by design". If that's the case, I think is a good ideia to add a note to the docs, mentioning this. On the other hand, if possible, I think that respect the language variations would be the best choice. 

I did change the code from 
```python
current_language_code = self.current_lang.replace('_', '-').split('-')[0]
```
to 
```python
current_language_code = self.current_lang.replace('_', '-')
```

and it dit work with my tree named _maintree_pt-br_, but I'm not sure how to run the sitetree tests, to be sure that I didn't messed up anything...

I'll be happy to help, if there is anything I can do for you on this issue...

**Comment by idlesign** [comment]
It seems to be by design, yet by now I can't say for sure why it so. First impression is that we can get rid of that split and it shouldn't break anything. Need a couple of days to skim through changes and think it over. 

You can use `tox` to run tests (in source tree root):
``> tox``

**Comment by idlesign** [comment]
Let's do it. Pull request with the improvement and test suite update is welcome.
