### ISSUE TITLE
Reordering tree items broken

### ISSUE THREAD

**Issue by dolugen** [idlesign/django-sitetree#229]
Django==1.10.6
django-sitetree==1.7.0

Changing sort order isn't working properly. When you click on the up and down buttons, nothing happens. It loads the `/admin/sitetree/tree/1/change/item_5/move_up/` and redirects back to the page, but nothing happens. But, when you save a _new_ tree item, and go back to the tree page, you can see that the previously reordered item has changed place.

**Comment by idlesign** [comment]
It does, as from your description. See you webserver and browser caching settings.
Try  Ctrl+F5 in your browser after move up/down, to verify.

**Comment by idlesign** [comment]
That also might be app caching issue. I'll try to verify that this week too.

**Comment by dolugen** [comment]
The project is a newly created one, no fancy settings, and is running on the development server. Ctrl+F5 doesn't help.

**Comment by dolugen** [comment]
I see that sitetree uses some heavy caching:
```
CACHE_TIMEOUT = getattr(settings, 'SITETREE_CACHE_TIMEOUT', 31536000)
"""Sitetree objects are stored in Django cache for a year (60 * 60 * 24 * 365 = 31536000 sec).
Cache is only invalidated on sitetree or sitetree item change.
"""
```

So I set `SITETREE_CACHE_TIMEOUT = 1` as a test, and tried reordering, and what do you know, it works.

Does this mean that the tree caches are not being properly invalidated?

**Comment by dolugen** [comment]
From the Performance docs:

> Note:
> Sitetree uses Django cache framework to store trees data, but keep in mind that Django’s default is Local-memory caching that is known not playing well with multiple processes (which will eventually cause sitetree to render navigation in different states for different processes), so you’re advised to use the other choices.

So this is sort of a known problem. Changing cache backend to `DummyCache` works too. Alright, I'll close this one. Maybe the above note should be pinned on the Getting Started page...
