### ISSUE TITLE
Redirect to tree page instead of tree list

### ISSUE THREAD

**Issue by dolugen** [idlesign/django-sitetree#231]
In the admin section, when you "save" an already created tree item page, you're redirected to the tree page. 

But, when you just "save" a new tree item, you're redirected to the tree list. I don't know if it's intentional, but I think it's better to have the former behavior for both action.

**Comment by idlesign** [comment]
Thank you for the report.
No this is not intentional. It is probably due to some admin change in recent Django versions.

Fixes with test suite imprevements are welcome!
