### ISSUE TITLE
Django 1.11 render prohibits non-dict context

### ISSUE THREAD

**Issue by nakato** [idlesign/django-sitetree#232]
https://docs.djangoproject.com/en/1.11/releases/1.11/#django-template-render-prohibits-non-dict-context

This means sitetree.templatetags.sitetree:render and other renders that use a Context or RequestContext fail.

**Comment by idlesign** [comment]
Thank you.
Some preparations for this change are already in the codebase since 1.6. 
More to come.

**Comment by berkerpeksag** [comment]
This also raises a deprecation warning in Django 1.9:

```
/path/to/sitetree/templatetags/sitetree.py:304: RemovedInDjango110Warning: render() must be called with a dict, not a RequestContext.
  content = get_template(use_template).render(context.flatten() if _CONTEXT_FLATTEN else context)
```

**Comment by nakato** [comment]
_CONTEXT_FLATEN is only True if Django Version is 1.11 or greater, as such it's still a RequestContext, and will continue to be called with a RequestContext until it is running with Django version 1.11.

It appears to me to be safe to ignore the warning.

---

As an aside, I can confirm the 1.8 release is good and working for me on 1.11, as far as I'm concerned this issue can be closed.

Thanks for your work idlesign.

**Comment by idlesign** [comment]
Thank you, @nakato. 
Considered closed.
