### ISSUE TITLE
#unresolved ?

### ISSUE THREAD

**Issue by Barolina** [idlesign/django-sitetree#235]
В админке создала item 
->  books-add books.pk
       ->   books-add books.pk

Но на странице   при нажатии на добавить , получается ссылка  "http:// .... /**#unresolved**

**Comment by idlesign** [comment]
Маркер `#unresoved` указывает на то, что не удалось вычислить URL для данного элемента дерева на данной странице. Скорее всего, в контексте шаблона страницы, на которой отрисовывается данный элемент дерева, нет переменной `books` (или нет атрибута `pk`).

В целом же, в большинстве случаев, для страниц создания чего-либо составлять URL, используя идентификатор /первичный ключ сущности — излишне, потому что на место `books.pk` в лучшем случае (на странице создания сущности) встанет `None`, в худшем (на других страницах, отрисовывающих данный элемент дерева) в контексте не окажется нужной переменной. 

Таким образом, `books-add` должно быть достаточно.

**Comment by idlesign** [comment]
Закрываю. Если вопрос не исчерпан, можете открыть повторно.
