### ISSUE TITLE
Render menu title?

### ISSUE THREAD

**Issue by quevon24** [idlesign/django-sitetree#236]
Hi, I was wondering if it's possible to render the menu title/alias (not the menu item title) because I'm creating a custom template for a sitetree_menu but I want to render title above the menu items.

**Comment by idlesign** [comment]
Hi, currenlty there's no dedicated template tag to do that.
Yet you can try to address tree object from the very first tree item in your template, like: `items[0].tree.alias`.

**Comment by quevon24** [comment]
Thanks for your answer, I achieved it this way: {{ sitetree_items.0.tree.title }}

Also other question, why permission restriction for item doesn't take in case if user is superuser, I think that should show all items if user is superuser even if the item has permission restriction.

**Comment by idlesign** [comment]
You're welcome.

Many years ago somehow it was decided that superuser has no superpowers in respect to sitetree items access. It may be wrong for some cases and useful for other, yet it'd be a backward incompatible thing to introduce now.

**Comment by quevon24** [comment]
Thanks for your answer, I made a monkey patch to override check_access method, just added:

    if self.current_request.user.is_superuser:
        return True
