### ISSUE TITLE
Abnormal number of queries when add item

### ISSUE THREAD

**Issue by quevon24** [idlesign/django-sitetree#237]
Hi I want to report a problem with the module, when I go to add a new item to my menu (admin/sitetree/tree/7/change/item_add/) and also when click ok save and add other django debug toolbar reports a lot of queries, and some of them duplicated, like this:

SELECT ••• FROM `django_content_type` WHERE `django_content_type`.`id` = 15  
Duplicated 369 times.

SELECT ••• FROM `django_content_type` WHERE `django_content_type`.`id` = 16  
Duplicated 369 times.

SELECT ••• FROM `django_content_type` WHERE `django_content_type`.`id` = 42 
Duplicated 369 times.

And those queries happens for all content types

Because of this, add a new item takes at least 16 seconds to load or to post.

If you only save the new item, module add it fast, but if you save and continue editing or save and add other, behaves the same, almost 16 seconds to load the page.

**Comment by idlesign** [comment]
Hi,
Sitetree uses content types for permissions. 
Do you have 300+ permissions that you use for one sitetree item?

**Comment by quevon24** [comment]
Yes, I have more than 350 permissions in my app, but only use a few ones (up to 5) on each sitetree item.

**Comment by idlesign** [comment]
I'll take a look, when I have more time.

**Comment by idlesign** [comment]
Changes are made, you can try it in `master`.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
