### ISSUE TITLE
Convert template context processor exception to a system check

### ISSUE THREAD

**Issue by berkerpeksag** [idlesign/django-sitetree#238]
Currently, I get the following exception everytime something went wrong when rendering a view:

```
sitetree.exceptions.SiteTreeError: Sitetree requires "django.core.context_processors.request" template context processor to be active. If it is, check that your view pushes request data into the template.
```

See https://travis-ci.org/python/pythondotorg/builds/276126958 for an example.

It makes debugging a lot harder and it would be better to have it as a system check: https://docs.djangoproject.com/en/1.11/topics/checks/#writing-your-own-checks

**Comment by idlesign** [comment]
This one is the same as #167
Systems checks are static checks, I see no way to use them dynamically. What's your proposal?

By now `request` processor has been in `context_processors` defaults for quite a time, we could just drop that `raise`, except it would do us a little good.

**Comment by berkerpeksag** [comment]
Thank you for the quick response. I agree with you.

Since `render_to_string()` and its friends have been deprecated, and the suggested way (`django.shortcuts.render`) is already taken care of passing `context` into template, I think that `raise` can be dropped or turned into a `UserWarning`.

**Comment by idlesign** [comment]
Warning might be of use indeed.
If it solves the issue, pull request is welcome with tests showing the problem is gone.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
