### ISSUE TITLE
It's posible to hide parent but show children in Breadcrumb?

### ISSUE THREAD

**Issue by joeljv91** [idlesign/django-sitetree#241]
Hi

I'm working on a project with Django 1.10 and Django CMS and I have a page with this site tree "About --> What is this?" but, in breadcrumb I only want to show "Home --> What is this?"

I test the hide in breadcrumb option but if I hide the parent the children doesn't show.

Thanks!

**Comment by idlesign** [comment]
Hi,

I'd recommend you using css or js. If that's not enough customized template is the ticket.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
