### ISSUE TITLE
When deleting in admin you need to restart app to see efect

### ISSUE THREAD

**Issue by m32w** [idlesign/django-sitetree#245]
Hello,

I found issue which is, for now, I do not know how to fix, when you delete item in admin view, you still see position, you can not click in it as you will see the message "item does not exist", but only app restart helps to have them removed from admin panel.

**Comment by idlesign** [comment]
Hi,

What cache backend is used?

**Comment by agronick** [comment]
@m32w They're only clearing the cache on one thread. All the other threads are left with a stale cache. I added timestamps to fix this: https://github.com/agronick/django-sitetree

**Comment by jacobbridges** [comment]
@agronick Care to make a pull request? I ran into this problem earlier today and was confused for a while.

**Comment by agronick** [comment]
Me and this dude didn't get along too well. I tried helping him out for over a year. I finally gave up. I've been using my modified version in production for several years with no issues.
