### ISSUE TITLE
Add submenu support for Bootstrap menu

### ISSUE THREAD

**Issue by PetrDlouhy** [idlesign/django-sitetree#246]
The `menu_bootstrap3` template render only one level of menu - it stops the recursion in first submenu.
There is example, how to make multi-level submenu with addition of little CSS: https://codepen.io/ajaypatelaj/pen/prHjD

I was able to achieve that with slight change of the `menu_bootstrap3_dropdown.html` template:
```
{% load sitetree %}
<ul class="dropdown-menu" role="menu">
    {% for item in sitetree_items %}
       <li role="presentation" class="{% if item.has_children %}dropdown-submenu{% endif %} {% if item.is_current or item.in_current_branch %}active{% endif %}">
            <a role="menuitem" href="{% sitetree_url for item %}" {% if item.hint %}title="{{ item.hint }}"{% endif %}>{{ item.title_resolved }}</a>
            {% if item.has_children %}
                {% sitetree_children of item for menu template "sitetree/menu_bootstrap3_dropdown.html" %}
            {% endif %}
        </li>
    {% endfor %}
</ul>
```

I would like to publish this change for wider audition. I have following possibilities:

- Submit pull request to `django-sitetree` only with this change. Without the CSS this doesn't change anything for the end user, so I would only mention that in docs.
- Submit PR with this change and the CSS (which would need to be manually added), and document it.
- Make standalone package.

Which way do you prefer?

**Comment by idlesign** [comment]
Hi,

Thank you. 
I would propose a separate template (say, ``menu_bootstrap3_dropdown_deep.html``) and mentioning it in the documentation (with CSS required for this to proper function). It will require a custom menu template, but that seems to be OK.

PR is welcome.
