### ISSUE TITLE
Resolving non-ascii URL

### ISSUE THREAD

**Issue by hiimdoublej** [idlesign/django-sitetree#253]
Hi, good job maintaining this project, however I would like to have a question answered as I think I'm missing something here but couldn't quite figure it out by myself.  
### What I did:
So, in my template I have this variable that I can access using ``` {{ divisions.major }}```,
I also have a url pattern named ```'major_division'```, which takes one argument ```major_division```,
I put ``` 'major_division divisions.major'``` into url of a site tree item.
```URL as Pattern``` is checked in additional settings.
### What happended:
it resolved into ```/divisions.major``` 
### What I was expecting: 
I expected it to evaluate the variable, and resolve into ```/<some_major_region>```

How can I do that using this package ? Thank you.

**Comment by idlesign** [comment]
Hi. Thank you.

If all views, that render the menu with this item, have `divisions.major` in context, this behaviour seems wierd. I'd rather expect to see `unresolved` marker than that.

Please share you tree branch (e.g. screenshot) leading to the item with `major_division divisions.major` as URL, alongside with an excerpt from `urls`.

**Comment by hiimdoublej** [comment]
[my site tree items](https://imgur.com/65VJjpW)
[corresponding urls](https://imgur.com/Me94MB2)
When I visit the last page in this tree, using the 
```{% sitetree_breadcrumbs from "com_tree" %}``` tag would resolve into this HTML structure:
```
<ul>	
		<li><a href="SITE_INDEX_URL">SITE_TITLE</a></li>
		<li>&gt;</li>	
		<li><a href="/jobs-in-divisions.major">台北市</a></li>
		<li>&gt;</li>	
		<li><a href="/jobs-in-divisions.major-divisions.minor">內湖區</a></li>
		<li>&gt;</li>	
		<li>福站便利商店</li>
</ul>
```
The variables that are titles of a tree node have all resolved correctly, just unsure why it would not resolve in the urls.
How are the tree node urls being resolved in your package, if I may ask ?
Thanks.

**Comment by idlesign** [comment]
Tried to reproduce the behaviour but without any luck, urls are resolved as expected:
![resolution](https://user-images.githubusercontent.com/145644/45581970-fb625000-b8d1-11e8-9e19-452b3c9aa92c.png)

It may somehow be related to views, but it's hard to be sure without debugging actual code.
If that helps, url resolutions happen here - https://github.com/idlesign/django-sitetree/blob/master/sitetree/sitetreeapp.py#L635

**Comment by hiimdoublej** [comment]
Thank you for your efforts in attempt to reproduce the issue, I appreciate it.
I took a look at the link you gave me, and in [line 665 of sitetreeapp.py](https://github.com/idlesign/django-sitetree/blob/master/sitetree/sitetreeapp.py#L665) 
I see you commented ``` # In case of non-ascii data we leave variable unresolved.```
What does that mean? I think it could be related since all my strings are and will be in utf-8, since they're Chinese. Maybe try changing the variables to a utf-8 chinese word (like the ones that I provided in my previous comment) would hep you reproduce the issue?

**Comment by hiimdoublej** [comment]
@idlesign Your magic branch worked ! I uninstalled the pypi version and installed your branch from a checkout zip, fired up the same page to test. The following HTML code are the correct results I expect now, as compared to my previous comments. It resolved the variables correctly just like how the built in ```url``` tag would resove. Kudos to you for the speedy response. Thanks again.
```
<ul>
	<li><a href="SITE_INDEX_URL">SITE_TITLE</a></li>
	<li>&gt;</li>
	<li><a href="/jobs-in-%E5%8F%B0%E5%8C%97%E5%B8%82">台北市</a></li>
	<li>&gt;</li>
	<li><a href="/jobs-in-%E5%8F%B0%E5%8C%97%E5%B8%82-%E5%85%A7%E6%B9%96%E5%8D%80">內湖區</a></li>
	<li>&gt;</li>
	<li>苗林實業有限公司</li>
</ul>
```

**Comment by idlesign** [comment]
1.12 is out with the change.
Considered closed. 
Feel free to reopen if required.

**Comment by hiimdoublej** [comment]
@idlesign Thank you. I consider this closed as well :)
