### ISSUE TITLE
"hook" into tree with app

### ISSUE THREAD

**Issue by nerdoc** [idlesign/django-sitetree#256]
It's more a question than a bug - maybe I didn't get it (or the docs aren't clear about that?), but:

**How can I  use different apps to "hook" into the main tree?**

Use the case: I create an app with a sitetrees.py, using the following content:
```python
from sitetree.utils import tree, item

sitetrees = (
    tree("maintree", items=[
        item("File", "#"), children=[
            item('New', 'base:newfile')
        ],
        item("Extras", "#", children=[
            item('Test', 'another_namespace:test_function')
        ]),
    ]),
)
```

Now I want to create a "plugin" app for that Django application, that provides an `File/Open` menu, and create a "open" app `./manage.py startapp open` - with another sitetrees.py:

```python
from sitetree.utils import tree, item

sitetrees = (
    tree("maintree", items=[
        item("File", "#"), children=[
            item('Open', 'base:openFile')
        ]
    ]),
)
```

It's obvious that this does not work, as it will overwrite the first maintree.
How do I achieve that there are both, *New* and *Open*, under the *File* menu then?

Or is this not possible?
Thanks.

**Comment by idlesign** [comment]
Considered closed.
