### ISSUE TITLE
Не получается вывести breadcrubs с шаблонным url [RUS]

### ISSUE THREAD

**Issue by Miza01** [idlesign/django-sitetree#261]
Здравствуйте. Спасибо за хорошую надстройку.Использую Django 2.1.5. Создаю вот такую иерархию для хлебных крошек.
![image](https://user-images.githubusercontent.com/16014043/53504248-a6eb0f80-3ac2-11e9-8aa9-7e3bcbf985b7.png)
Создаю шаблоны юрлов:
```
urlpatterns = [
    #  path('catalog/<str:category>/<int:item>/', views.item, name='item'),
    re_path(r'^catalog/(?P<category>\S+)/(?P<item>\S+)/$', views.item, name='item'),
]
```
И вписываю тег в шаблон 
```
{% load sitetree %}

<div class="row">
    <div class="col-12 breadcrumbs-wrap ">
        <div class="breadcrumbs">
            {% sitetree_breadcrumbs from "breadcrumbs" %}
        </div>
    </div>
</div>
```
Но ничего не отображается на странице, хотя крошки без шаблонного url отображаются.
Ваша надстройка работает на Django 2+?

**Comment by idlesign** [comment]
Здравствуйте. 

Да, 2+ поддерживается: например для демо (https://github.com/idlesign/django-sitetree/tree/master/demo) по умолчанию сейчас ставится 2.1.2.

Удостоверьтесь, что 
* элемент дерева помечен, как использующих шаблонный узел
* в шаблон приходят ``category`` и ``item``, которые, согласно вашему шаблону URL должны быть строкой и целым соответственно (есть подозрение, что там у вас другие объекты, если они вообще есть), либо замените в описании элемента дерева ``item category item``на что-то типа ``item category.alias item.id``.

**Comment by Miza01** [comment]
Я заменил в описании дерева 
    * item category item
последний item на item_id и все заработало

**Comment by idlesign** [comment]
Пожалуйста.
Закрываю.
