### ISSUE TITLE
Как проверить доступные элементы меню у конкретного пользователя [RUS]

### ISSUE THREAD

**Issue by brestows** [idlesign/django-sitetree#270]
Добрый день, подскажите как правильно получить все элементы меню доступные конкретному пользователю ? 

Я пробую сделать так: 
```
tree_address_book = getattr(import_app_sitetree_module('addressbook'), 'sitetrees', None)
allow_item = []
if tree_address_book:
     for item in tree_address_book[0].dynamic_items:
          if user.has_perms(item.permissions, obj=item):
              allow_item.append(item.alias)
```

это это коряво и очень не оптимально, но все равное не работает ( 
В документации не нашел описание как это проверить.

**Comment by idlesign** [comment]
Доброго дня,

Выделенного API для таких проверок нет, можно определить своего наследника `SiteTree` и использовать методы родителя.

Если бы вы описали цель, чего хотите добиться, вероятно можно было бы предложить какое-то другое решение.

**Comment by brestows** [comment]
Есть проект на Django, в котором я использую ваш модуль для управления меню, с ним я сбольшего разобрался и меня он более чем устраивает, все работает как надо. В этом проекте есть приложение, которое представляет собой адресную книгу, данные для которой берутся из ActiveDirectory. Корневой элемент адресной книги называется 'addressbook' у него есть 15-20 дочерних элементов. У каждого дочернего элемента, есть индивидуальные права (не все пользователи должны иметь доступ ко всем дочерним элементам адресной книги). 
К примеру есть дочернии элементы 
Минск
Москва
Питер
Киев
Варшава

Есть пользователь Вася у которого доступ есть к элементу Минск и Киев, так же есть дочерный элемент "ALL" при вызове его пользователь Вася получает все контакты из доступных ему элементов (Минск и Киев). Но что бы сгенерировать данные для Васи, надо  получить от SiteTree доступные для него дочернии элементы 'addressbook'

Надеюсь не запутал Вас. 

Спасибо за Вашу помощь

**Comment by brestows** [comment]
Сделал так: 
```
 tree_address_book = getattr(import_app_sitetree_module('addressbook'), 'sitetrees', None)
allow_item = []
 if tree_address_book:
    for item in tree_address_book[0].dynamic_items:
         if getattr(item, 'parent', None):
              item_perms = item.permissions
              if user.has_perms(['{}.{}'.format(perm.content_type.model, perm.codename) for perm in item_perms]):
                   allow_item.append(item.alias)
```

**Comment by idlesign** [comment]
> Есть пользователь Вася у которого доступ есть к элементу Минск и Киев, так же есть дочерный элемент "ALL" при вызове его пользователь Вася получает все контакты из доступных ему элементов (Минск и Киев). Но что бы сгенерировать данные для Васи, надо получить от SiteTree доступные для него дочернии элементы 'addressbook'

Кажется, что этот случай поддерживается в шаблонах из коробки, если завести права для элемента дерева и выставить их для элементов. В функцию динамического создания элементов дерева можно передавать имена прав, которым должен обладать пользователь. Попробуйте.

**Comment by brestows** [comment]
Спасибо, буду пробовать.
