### ISSUE TITLE
First install it, then use it

### ISSUE THREAD

**Issue by guettli** [idlesign/django-sitetree#273]
Thank you for the great docs.

One hint. It would make sense to tell the users who to install the app before configuring settings.py

https://django-sitetree.readthedocs.io/en/latest/quickstart.html

**Comment by idlesign** [comment]
Thank you.
But have you read a classic INSTALL file?
https://github.com/idlesign/django-sitetree/blob/master/INSTALL

**Comment by guettli** [comment]
I read the docs from the beginning to the end. No, I did not read the INSTALL, and I can help myself. But the end user experience would feel more fluent if the docs are straight foward executable.

**Comment by idlesign** [comment]
If you feel it would improve the docs, no problem, let it be. Pull request is welcome.

**Comment by guettli** [comment]
I had time for feedback, but not for PR. Sorry.

**Comment by idlesign** [comment]
No problem. Thank you for the feedback.
