### ISSUE TITLE
More aligned docs

### ISSUE THREAD

**Issue by guettli** [idlesign/django-sitetree#275]
This page uses "topmenu": https://django-sitetree.readthedocs.io/en/latest/tags.html

This page uses "maintree": https://django-sitetree.readthedocs.io/en/latest/quickstart.html

I give you this feedback, because I like django-sitetree. Thank you for sharing it!

**Comment by idlesign** [comment]
Thank you.
Hm. Don't know how RTD handles this. 
Any ideas?

**Comment by guettli** [comment]
I am sorry. I don't understand your question. Both pages use different words in their example data. The user experience is simplier, if all examples use the same words. That's all.

**Comment by idlesign** [comment]
Ah, I see. 
The thing is those are different menus, and alias is just a matter of convenience, no need to stick to something.

But feel free to make a pull request, if you think it would be better.
