### ISSUE TITLE
Tree items not displayed in menu if url contains certain special characters

### ISSUE THREAD

**Issue by sandracioc** [idlesign/django-sitetree#288]
Hello, my nav menu is made up of a main title(home page) at the top and a few tree items.
When I try to access a page in which the url contains at least one special character, the tree items are not shown anymore in the menu, just the main title. 

Some special characters that I found interfering with the correct display of the menu are:  = + { } ( ) : ; '
But these characters don't interfere:  [ ] ? < > |
I should mention my url regex is set to include all of the characters above.

I tried replacing the characters in the url with their ASCII equivalents but nothing changed.

Been having this issue for a long time and I really don't know what could be causing it.

Thanks in advance for your help.

**Comment by idlesign** [comment]
Hi,

Please provide:
* tree items definitions
* an urlpattern you use
* an URL to reproduce (by the way, is it urlencoded?)

**Comment by sandracioc** [comment]
Hello,

Tree items definitions:
<table>
<tr><td>Title</td><td>URL</td> </tr>
<tr><td>HOME</td><td>private</td></tr>
<tr><td>|— About</td><td>about</td></tr>
<tr><td>  |— Reports</td><td>reports</td></tr>
<tr><td>|— Reports |— Products</td><td>products</td></tr>
<tr><td>|— Reports |— Products |— Devices</td><td>products:devices  </td></tr>
<tr><td>|— Reports |— Products |— Devices |— Devices {{ grp }}</td><td>products:devices_grp grp</td></tr>
</table>

URL pattern:  `r'^devices/(?P<grp>([() 0-9a-zA-Z!*:.?+=_-])+)$'`

URL:  `/private/products/devices/Device10x 45.9(2)S5/`   It is not urlencoded.

Thank you.

**Comment by idlesign** [comment]
That was an old one indeed %) Thank you for the report.
Seems to be fixed in `master`. You may want to give it a try.

**Comment by sandracioc** [comment]
Verified it and it's fixed. Thank you, @idlesign! Closing the issue.
