### ISSUE TITLE
compose_dynamic_tree with access_by_perms called in `config.ready` results in database errors

### ISSUE THREAD

**Issue by wkleinheerenbrink** [idlesign/django-sitetree#302]
Hi! 

Thanks for this nice package. I found a caveat in the docs resulting in a bug:

### Reproduction steps, given a simple app:

1. Go to your AppConfig
2. Create a method `ready()` and define a dynamic site structure as define in https://django-sitetree.readthedocs.io/en/latest/apps.html#dynamic-sitetree-structuring
3. Add `access_by_perms=["auth.add_user"])` to `item('dynamic_2', 'dynamic_2_url', access_by_perms=["auth.add_user"])`
3. Now make sure you database is empty and don't run `python manage.py migrate`
4. Run `python manage.py makemigrations --check` (or any other management command)

### Expected result
Management command responds with now migrations to create.

### Actual result
Exception: Non-existing Auth Permissions table in databse. Something like:
```
django.db.utils.ProgrammingError: relation "auth_permission" does not exist
LINE 1: ...ntent_type_id", "auth_permission"."codename" FROM "auth_perm...
```

### Cause
This is caused by the fact that Django calls `app_ready()` each time a (random) Django Command is run. This can be `runserver`, `migrate` etc. This will be no problem, until you start working with a fresh database, for instance in a test-server environment.

Django docs state:

> ### Warning
> Although you can access model classes as described above, avoid interacting with the database in your ready() implementation. This includes model methods that execute queries (save(), delete(), manager methods etc.), and also raw SQL queries via django.db.connection. Your ready() method will run during startup of every management command. For example, even though the test database configuration is separate from the production settings, manage.py test would still execute some queries against your production database!
> https://docs.djangoproject.com/en/3.2/ref/applications/#django.apps.AppConfig.ready

I haven't thought of a better place to put the dynamic registering of the menu. Once I do I'll post it here. Perhaps someone has a great idea already.

**Comment by idlesign** [comment]
Hi.
Thank you.

I'd say this behaviour is expected, but indeed may be it needs to be accentuated in the docs somehow.
See, if you use some permissions in your trees, those are expected to exist. This means that Auth contrib related tables need to be in place before we can operate our trees. It's obviously not the case when our DB is empty.

> For example, even though the test database configuration is separate from the production settings, manage.py test would still execute some queries against your production database!

Two points here:
1. There shouldn't be any data-destructive queries made by sitetree;
2. Personally I've switched from manage.py test to pytest-django and further to pytest-djangoapp a long time ago. The later uses SQLite DB in memory by default for test to achieve stable results.

**Comment by wkleinheerenbrink** [comment]
Thanks for your response and suggestion for using `pytest-django` (and `python-djangoapp`). I will definitely try this.

I did some more research and found that this happens in each case when calling `manage.py`. This includes the case where you call `python manage.py migrate` on an empty database, making it impossible to scaffold your database at all.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
