### ISSUE TITLE
Template filter "length_is" causes incompatibility with Django 5.1

### ISSUE THREAD

**Issue by simklei** [idlesign/django-sitetree#320]
Multiple breadcrumbs templates ((7, according to [search results](https://github.com/search?q=repo%3Aidlesign%2Fdjango-sitetree+length_is&type=code))) make use of the now removed `length_is` Django template filter. When using django-sitetree in a Django project with version 5.1, this causes the error message `django.template.exceptions.TemplateSyntaxError: Invalid filter: 'length_is'`. Downgrading to Django 5.0 resolves the issue.

The `length_is` filter was deprecated in Django 4.2 ([release notes, with suggested fix](https://docs.djangoproject.com/en/5.1/releases/4.2/#id1)), and fully removed in Django 5.1 ([release notes](https://docs.djangoproject.com/en/5.1/releases/5.1/#features-removed-in-5-1)).

The suggested fix is to replace `value|length_is:x` with `value|length == x`, replacing `value` and `x` with the context variable and an integer, respectively. For example, `sitetree_items|length_is:"1"` -> `sitetree_items|length == 1`.

**Comment by idlesign** [comment]
Thank you for the report.

It also seems that we need to extend CI configuration for Django 5.1 (https://github.com/idlesign/django-sitetree/blob/master/.github/workflows/python-package.yml#L18).

By the way, pull request is welcome.

**Comment by simklei** [comment]
I'm working on a fix, will make a PR when it's ready.
