### ISSUE TITLE
feature request: add an "icon" field to the sitetree item model to render in templates

### ISSUE THREAD

**Issue by scottwoodall** [idlesign/django-sitetree#91]
Within several of my navigations and menus I prefer to have icons from frameworks like twitter bootstrap or font awesome along side the text:

![Screen Shot 2013-02-05 at 9 01 15 AM](https://f.cloud.github.com/assets/620454/127492/956c37b8-6f9c-11e2-903d-e810c82f905d.png)

I'm currently leveraging one of the existing sitetree item model fields to put the name of an icon ("icon-bullhorn") and then overriding the existing template so they show up.

Thoughts? Do you like the idea and would you be willing to accept a pull request? And if so, anything I need to know before starting?

**Comment by PetrDlouhy** [comment]
I implemented the icons with font-awesome - the only thing that needs to be done to make it working is to override the `menu_bootstrap3.html` template and make the header behave as safe:
`{{ item.title_resolved }}` -> `{{ item.title_resolved|safe }}`

I am not sure, if it could be used generally (maybe users can edit menu in some projects), but usually it is easiest solution.
